version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - URLSHORTENER_PORT=8080        
      - URLSHORTENER_DOMAIN=localhost:8080      
      - URLSHORTENER_EXPIRY=162h      
      - URLSHORTENER_DATABASE_URL=postgres://postgres:example@postgres:5432/urlshortener
    depends_on:
      - postgres
    networks:
      - shared-network

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=urlshortener
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d/
    networks:
      - shared-network

volumes:
  postgres-data:

networks:
  shared-network:
